### ISSUE TITLE
去掉表格的标题

### ISSUE THREAD

**Issue by liliangqi** [corenel/ZJUProposal#3]
如题，请问如何去掉表格的标题，就是连“表1”都不要出现

**Comment by corenel** [comment]
浮动体内不用`\caption`即可。

**Comment by liliangqi** [comment]
@corenel 您好，若是不用\caption的话会报错：
Package hypcap Error: You have forgotten to use \caption.

**Comment by corenel** [comment]
你不需要的话可以直接去掉hypcap宏包，或者使用[这里](https://tex.stackexchange.com/questions/240239/keep-getting-package-hypcap-error-you-have-forgotten-to-use-caption-error-f)的方法解决。
请善用搜索。
